import type { CreatorProfile, PageParams, Paginated } from "@naano/shared";
import type { ApiClient } from "./client";

const FIXTURE_CREATORS: CreatorProfile[] = [
  {
    id: "fixture-1",
    userId: "fixture-user-1",
    displayName: "Sofia Bergman",
    headline: "RevOps systems that keep GTM data honest",
    avatarUrl: null,
    vertical: "REVOPS",
    followerCount: 42_000,
    country: "SE",
    language: "en",
    pricePerPostCents: 22_000,
    avgImpressions: 9_000,
    engagementRate: 0.041,
    createdAt: "2026-08-01T09:00:00.000Z",
  },
  {
    id: "fixture-2",
    userId: "fixture-user-2",
    displayName: "Marco Conti",
    headline: "Writing for developers who hate marketing",
    avatarUrl: null,
    vertical: "DEVTOOLS",
    followerCount: 128_000,
    country: "IT",
    language: "it",
    pricePerPostCents: 45_000,
    avgImpressions: 20_000,
    engagementRate: 0.035,
    createdAt: "2026-08-03T09:00:00.000Z",
  },
  {
    id: "fixture-3",
    userId: "fixture-user-3",
    displayName: "Amelia Reyes",
    headline: "Fintech and embedded finance, explained simply",
    avatarUrl: null,
    vertical: "FINTECH",
    followerCount: 310_000,
    country: "GB",
    language: "en",
    pricePerPostCents: 95_000,
    avgImpressions: 100_000,
    engagementRate: 0.028,
    createdAt: "2026-08-05T09:00:00.000Z",
  },
  {
    id: "fixture-4",
    userId: "fixture-user-4",
    displayName: "Nils Andersen",
    headline: "Outbound sales playbooks that actually convert",
    avatarUrl: null,
    vertical: "SALES",
    followerCount: 8_500,
    country: "DK",
    language: "en",
    pricePerPostCents: 4_000,
    avgImpressions: 1_800,
    engagementRate: 0.052,
    createdAt: "2026-08-07T09:00:00.000Z",
  },
  {
    id: "fixture-5",
    userId: "fixture-user-5",
    displayName: "Ines Moreau",
    headline: "People ops and HR tech for modern teams",
    avatarUrl: null,
    vertical: "HR_TECH",
    followerCount: 61_000,
    country: "FR",
    language: "fr",
    pricePerPostCents: 31_000,
    avgImpressions: 12_500,
    engagementRate: 0.038,
    createdAt: "2026-08-09T09:00:00.000Z",
  },
  {
    id: "fixture-6",
    userId: "fixture-user-6",
    displayName: "Erik Larsen",
    headline: "Vertical SaaS go-to-market playbooks",
    avatarUrl: null,
    vertical: "VERTICAL_SAAS",
    followerCount: 19_000,
    country: "NL",
    language: "en",
    pricePerPostCents: 12_000,
    avgImpressions: 4_200,
    engagementRate: 0.044,
    createdAt: "2026-08-11T09:00:00.000Z",
  },
];

export const fixturesClient: ApiClient = {
  async listCreators(params?: PageParams): Promise<Paginated<CreatorProfile>> {
    const page = params?.page ?? 1;
    const pageSize = params?.pageSize ?? 20;
    const start = (page - 1) * pageSize;
    return {
      items: FIXTURE_CREATORS.slice(start, start + pageSize),
      total: FIXTURE_CREATORS.length,
      page,
      pageSize,
    };
  },
};
