import type { CreatorProfile, PageParams, Paginated } from "@naano/shared";
import type { ApiClient } from "./client";

// Static stand-in for the API. Kept in the same shape as the live payload so
// swapping VITE_API_MODE is the only change. Figures follow the calibration in
// docs/RECON.md §10: median views 20-100% of followers, CPM in the EUR 10-30
// band, bundle of five ~3.3x a single post.
const FIXTURE_CREATORS: CreatorProfile[] = [
  {
    id: "fixture-1",
    userId: "fixture-user-1",
    displayName: "Sofia Bergman",
    headline: "RevOps systems that keep GTM data honest",
    avatarUrl: null,
    vertical: "REVOPS",
    network: "LINKEDIN",
    followerCount: 42_000,
    country: "SE",
    language: "en",
    postCostCents: 38_000,
    bundle5PriceCents: 125_400,
    medianViews: 19_000,
    observedEngagerCount: 62,
    postsAnalyzed: 22,
    engagementRate: 0.041,
    createdAt: "2026-08-01T09:00:00.000Z",
  },
  {
    id: "fixture-2",
    userId: "fixture-user-2",
    displayName: "Marco Conti",
    headline: "Writing for developers who hate marketing",
    avatarUrl: null,
    vertical: "DEVTOOLS",
    network: "X",
    followerCount: 128_000,
    country: "IT",
    language: "it",
    postCostCents: 99_000,
    bundle5PriceCents: 326_700,
    medianViews: 45_000,
    observedEngagerCount: 141,
    postsAnalyzed: 19,
    engagementRate: 0.035,
    createdAt: "2026-08-03T09:00:00.000Z",
  },
  {
    id: "fixture-3",
    userId: "fixture-user-3",
    displayName: "Amelia Reyes",
    headline: "Fintech and embedded finance, explained simply",
    avatarUrl: null,
    vertical: "FINTECH",
    network: "LINKEDIN",
    followerCount: 310_000,
    country: "GB",
    language: "en",
    postCostCents: 139_200,
    bundle5PriceCents: 459_360,
    medianViews: 87_000,
    observedEngagerCount: 204,
    postsAnalyzed: 17,
    engagementRate: 0.028,
    createdAt: "2026-08-05T09:00:00.000Z",
  },
  {
    id: "fixture-4",
    userId: "fixture-user-4",
    displayName: "Nils Andersen",
    headline: "Outbound sales playbooks that actually convert",
    avatarUrl: null,
    vertical: "SALES",
    network: "LINKEDIN",
    followerCount: 8_500,
    country: "DK",
    language: "en",
    postCostCents: 9_500,
    bundle5PriceCents: 31_350,
    medianViews: 6_800,
    observedEngagerCount: 34,
    postsAnalyzed: 24,
    engagementRate: 0.052,
    createdAt: "2026-08-07T09:00:00.000Z",
  },
  {
    id: "fixture-5",
    userId: "fixture-user-5",
    displayName: "Ines Moreau",
    headline: "People ops and HR tech for modern teams",
    avatarUrl: null,
    vertical: "HR_TECH",
    network: "LINKEDIN",
    followerCount: 61_000,
    country: "FR",
    language: "fr",
    postCostCents: 45_600,
    bundle5PriceCents: 150_480,
    medianViews: 24_000,
    observedEngagerCount: 88,
    postsAnalyzed: 20,
    engagementRate: 0.038,
    createdAt: "2026-08-09T09:00:00.000Z",
  },
  {
    id: "fixture-6",
    userId: "fixture-user-6",
    displayName: "Erik Larsen",
    headline: "Vertical SaaS go-to-market playbooks",
    avatarUrl: null,
    vertical: "VERTICAL_SAAS",
    network: "LINKEDIN",
    followerCount: 19_000,
    country: "NL",
    language: "en",
    postCostCents: 17_800,
    bundle5PriceCents: 58_740,
    medianViews: 10_500,
    observedEngagerCount: 47,
    postsAnalyzed: 21,
    engagementRate: 0.044,
    createdAt: "2026-08-11T09:00:00.000Z",
  },
];

export const fixturesClient: ApiClient = {
  async listCreators(params?: PageParams): Promise<Paginated<CreatorProfile>> {
    const page = params?.page ?? 1;
    const pageSize = params?.pageSize ?? 20;
    const start = (page - 1) * pageSize;
    return {
      items: FIXTURE_CREATORS.slice(start, start + pageSize),
      total: FIXTURE_CREATORS.length,
      page,
      pageSize,
    };
  },
};
